### ISSUE TITLE
Public resources (requiring no authentication)

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [DevNetSandbox/sbx_api_issues#2]
I noticed a few public resources (requiring no authentication)
- /sandbox
- /sandbox/ID/tile

Public resources should be treated carefully as they can be subject to attacks.

Are there good reasons to have these exposed publically? if not, I propose we turn these to protected (require authentication)

**Comment by TomDaviesUK** [comment]
Agreed. I think these should be protected, too.

@lookimapengu1 - Can we add this to the next release, please!

**Comment by lookimapengu1** [comment]
I think the reason that at least the /tile endpoint is public goes back to the fact that we need a better way to authenticate other DevNet apps/microsites/etc, since they would be the primary users for this one.  Not sure about the reasoning behind the /sandbox endpoint being public.  I'll add this to the to-do list!

**Comment by lookimapengu1** [comment]
All endpoints now require auth as of the current release.
